DefaultContentLanguage = "de"
baseURL = "https://www.katzug-rettungshundestaffel.at/hugo/"
disableLanguages = ["en"]
disqusShortname = ""
languageCode = "de-at"
paginate = "6"
summaryLength = "15"
theme = "kat-zug-rettungshundestaffel"
title = "Kat-Zug Rettungshundestaffel"
[Languages.de]
contentDir = "content/german"
copyright = "Copyright &copy; 2022 Alle Rechte vorbehalten"
home = "Home"
languageCode = "de-at"
languageName = "De"
weight = 1
[[Languages.de.menu.main]]
name = "Über uns"
url = "#about2"
weight = 1
[[Languages.de.menu.main]]
name = "Rettungshundearbeit"
url = "#rettungshundearbeit"
weight = 2
[[Languages.de.menu.main]]
name = "Staffel"
url = "#team"
weight = 3
[[Languages.de.menu.main]]
name = "Blog"
url = "#blog"
weight = 5
[[Languages.de.menu.main]]
name = "Kontakt"
url = "#contact"
weight = 6
[[Languages.de.menu.main]]
name = "Mitgliederbereich"
url = "mitgliederbereich"
weight = 7

[params]
author = "Themefisher"
description = "Responsive Multipurpose Parallax Hugo Template"
google_analytics_id = ""
logo = "images/logo.png"
logo_small = "images/logo_small.png"
post_share = true
[params.cookies]
enable = false
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = false
preloader = "images/logo.png"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/katzugrettungshundestaffel"

[taxonomies]
  category = 'categories'
  internal = 'internals'
  tag = 'tags'

