name: Deploy via FTP

on:
  push:
    branches:
    - master
  schedule:
    - cron:  '0 8 * * *' #every day at 8 am
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    - name: Build site
      run: cd exampleSite && hugo --gc --themesDir ../.. --minify

    - name: FTP site
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ftpBS.world4you.com/hugo/
        ftp-username: katzug-rettu
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: exampleSite/public
        git-ftp-args: --insecure --all
